/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author cosette
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Person person;
    public CreateJPanel(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtGeo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtDob = new javax.swing.JTextField();
        TxtBank = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtCert = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtVehicle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtTel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtDevice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtFax = new javax.swing.JTextField();
        TxtLinkedin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtInt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxtSsn = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtMed = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TxtBio = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TxtHealth = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TxtOther = new javax.swing.JTextField();
        BtnCreate = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Create your profile");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel3.setText("Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));
        add(TxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, -1));

        jLabel2.setText("Bank account numbers");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));
        add(TxtGeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 134, 150, -1));

        jLabel4.setText("Geographic data");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 112, -1, -1));

        jLabel5.setText("Date of birth");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 166, -1, -1));
        add(TxtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 188, 150, -1));
        add(TxtBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 80, 150, -1));

        jLabel6.setText("Certificate/license number");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 112, -1, -1));
        add(TxtCert, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 134, 150, -1));

        jLabel7.setText("Vehicle identifiers and serial numbers");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 166, -1, -1));

        TxtVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtVehicleActionPerformed(evt);
            }
        });
        add(TxtVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 210, 150, -1));

        jLabel8.setText("Telephone numbers");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));
        add(TxtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 242, 150, -1));

        jLabel9.setText("Device identifiers and serial numbers");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 242, -1, -1));

        jLabel10.setText("(including license plates)");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 188, -1, -1));
        add(TxtDevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 264, 150, -1));

        jLabel11.setText("FAX number");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 274, -1, -1));
        add(TxtFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 296, 150, -1));
        add(TxtLinkedin, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 318, 150, -1));

        jLabel12.setText("LinkedIn");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 296, -1, -1));

        jLabel13.setText("Email addresses");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 328, -1, -1));
        add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 150, -1));

        jLabel14.setText("Internet protocol addresses");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 350, -1, -1));
        add(TxtInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 372, 150, -1));

        jLabel15.setText("Social Security number");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 382, -1, -1));
        add(TxtSsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 404, 150, -1));

        jLabel16.setText("Biometric identifiers");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 404, -1, -1));
        add(TxtMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 458, 150, -1));

        jLabel17.setText("Medical record number");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 436, -1, -1));

        jLabel18.setText("(i.e. retinal scan, fingerprints)");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 426, -1, -1));
        add(TxtBio, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 448, 150, -1));

        jLabel19.setText("Health plan beneficiary number");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));
        add(TxtHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 512, 150, -1));

        jLabel20.setText("Full face photos and comparable images");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        jLabel21.setText("Any unique identifying number, characteristic, or code");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 544, -1, -1));
        add(TxtOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 566, 343, -1));

        BtnCreate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        BtnCreate.setText("create");
        BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateActionPerformed(evt);
            }
        });
        add(BtnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, 100, 50));

        btnBrowse.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        btnBrowse.setText("Browse...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 80, -1));
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 350, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtVehicleActionPerformed

    private void BtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateActionPerformed
        // TODO add your handling code here:
        person.setName(TxtName.getText());
        person.setGeoData(TxtGeo.getText());
        person.setDob(TxtDob.getText());
        person.setTeleNum(TxtTel.getText());
        person.setFax(TxtFax.getText());
        person.setEmail(TxtEmail.getText());
        person.setSsn(TxtSsn.getText());
        person.setMedNum(TxtMed.getText());
        person.setHealthNum(TxtHealth.getText());
        person.setBankAccNum(TxtBank.getText());
        person.setCertNum(TxtCert.getText());
        person.setVehicleNum(TxtVehicle.getText());
        person.setDeviceNum(TxtDevice.getText());
        person.setLinkedin(TxtLinkedin.getText());
        person.setIntAddress(TxtInt.getText());
        person.setBioId(TxtBio.getText());
        person.setOtherIdNum(TxtOther.getText());
        person.setPhoto(image.getIcon());
        
        //Prompt user that product was successfully created
        JOptionPane.showMessageDialog(null, 
                                      "Create person profile successfully!",
                                      "Warning",
                                      JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_BtnCreateActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        
        // Insert into Jlabel
        Image im = Toolkit.getDefaultToolkit().createImage(filename);
        im = im.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ii = new ImageIcon(im);
        image.setIcon(ii);
    }//GEN-LAST:event_btnBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreate;
    private javax.swing.JTextField TxtBank;
    private javax.swing.JTextField TxtBio;
    private javax.swing.JTextField TxtCert;
    private javax.swing.JTextField TxtDevice;
    private javax.swing.JTextField TxtDob;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtFax;
    private javax.swing.JTextField TxtGeo;
    private javax.swing.JTextField TxtHealth;
    private javax.swing.JTextField TxtInt;
    private javax.swing.JTextField TxtLinkedin;
    private javax.swing.JTextField TxtMed;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtOther;
    private javax.swing.JTextField TxtSsn;
    private javax.swing.JTextField TxtTel;
    private javax.swing.JTextField TxtVehicle;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
