/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PeiLingChiang
 */
public class ManageOrderJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem system;
    Restaurant restaurant;
    UserAccount userAccount;
    OrderRequest orderRequest;
    private int selectedRow;
    /**
     * Creates new form ManageOrderJPanel
     */
    public ManageOrderJPanel(JPanel userProcessContainer, Restaurant restaurant, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.restaurant = restaurant;
        this.userAccount = userAccount;
        this.system = system;
        populateTable();
        
        jComboBox.removeAllItems();
        Object[] array = system.getDeliveryManDirectory().getDeliveryManList().toArray();
        for(int i=0; i < array.length;i++){
            jComboBox.addItem(array[i].toString());
        }
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        model.setRowCount(0);
        for (OrderRequest or : userAccount.getWorkQueue().getOrderRequestList()){
            Object[] row = new Object[4];
            row[0] = or.getReceiver();
            row[1] = or.getOrderItem();
            row[2] = or.getStatus();
            row[3] = or.getDeliveryMan();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtOrder = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbAccept = new javax.swing.JCheckBox();
        cbDecline = new javax.swing.JCheckBox();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtReview = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Manage Orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 6, -1, -1));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Order", "Status", "DeliveryMan"
            }
        ));
        jScrollPane1.setViewportView(tblOrder);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 68, 520, 95));

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jLabel3.setText("Order");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        txtName.setEnabled(false);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 224, 89, -1));

        txtOrder.setEnabled(false);
        add(txtOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 256, 90, -1));

        jLabel4.setText("Approval");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        cbAccept.setText("Accept");
        cbAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAcceptActionPerformed(evt);
            }
        });
        add(cbAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        cbDecline.setText("Decline");
        cbDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDeclineActionPerformed(evt);
            }
        });
        add(cbDecline, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jLabel5.setText("DeliveryMan");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        txtReview.setEnabled(false);
        add(txtReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 200, -1));

        jLabel6.setText("Reveiw");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AdminWorkAreaJPanel adminwjp = (AdminWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        selectedRow = tblOrder.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        orderRequest = userAccount.getWorkQueue().getOrderRequestList().get(selectedRow);
        txtName.setText(orderRequest.getSender().toString());
        txtOrder.setText(orderRequest.getOrderItem());
        txtReview.setText(orderRequest.getMessage());
        
        if (orderRequest.getStatus().equals("Approved")){
            cbAccept.setSelected(true);
            cbAccept.setEnabled(false);
            cbDecline.setEnabled(false);
            jComboBox.setEnabled(false);
        }
        else if (orderRequest.getStatus().equals("Declined")){
            cbDecline.setSelected(true);
            cbAccept.setEnabled(false);
            cbDecline.setEnabled(false);
            jComboBox.setEnabled(false);
        }
        else if (orderRequest.getStatus().equals("Finished")){
            cbAccept.setSelected(false);
            cbAccept.setEnabled(false);
            cbDecline.setEnabled(false);
            jComboBox.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnSelectActionPerformed

    private void cbAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAcceptActionPerformed
        // TODO add your handling code here:
        if (cbAccept.isSelected()){
            cbDecline.setSelected(false);
        }
    }//GEN-LAST:event_cbAcceptActionPerformed

    private void cbDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDeclineActionPerformed
        // TODO add your handling code here:
        if (cbDecline.isSelected()){
            cbAccept.setSelected(false);
        }
    }//GEN-LAST:event_cbDeclineActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (cbAccept.isSelected()){
            orderRequest.setStatus("Approved");
        }
        else
            orderRequest.setStatus("Declined");
        
        for (DeliveryMan d : system.getDeliveryManDirectory().getDeliveryManList()){
            if (d.toString().equals(jComboBox.getSelectedItem())){
                orderRequest.setDeliveryMan(d);
                system.getUserAccountDirectory().findUser(d.getUsername()).getWorkQueue().getOrderRequestList().add(orderRequest);
            }
        }
        
        JOptionPane.showMessageDialog(null, "Successfully Submitted!!");
        populateTable();
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox cbAccept;
    private javax.swing.JCheckBox cbDecline;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrder;
    private javax.swing.JTextField txtReview;
    // End of variables declaration//GEN-END:variables
}
