/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;


import Business.Users.Admin;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author AEDSpring2019
 */
public class AdminCreateScreen extends javax.swing.JPanel {

    /**
     * Creates new form AdminScreen
     */
    private JPanel panelRight;
    private Admin admin;
    private AdminMainScreen prev_screen;
    private Border borderDefault;
    private Border borderWarn;
    
    
    public AdminCreateScreen(JPanel panelRight, Admin admin, AdminMainScreen prev_screen) {
        initComponents();
        this.panelRight = panelRight;
        this.admin = admin;
        this.prev_screen = prev_screen;
        borderDefault  =  txtRePword.getBorder();
        borderWarn = BorderFactory.createLineBorder(Color.red, 1);
    }
    
    private boolean usernamePatternCorrect(){
        Pattern p = Pattern.compile("^[a-zA-z0-9]+_[a-zA-z0-9]+@[a-zA-z0-9]+.[a-zA-z0-9]+$");
        Matcher m = p.matcher(txtUser.getText());
        return m.matches();
    }
    
    private boolean passwordPatternCorrect(){
        Pattern p = Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[*#$&])(?=\\S+$).{6,}$");
        Matcher m = p.matcher(txtPword.getText());
        return m.matches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        txtPword = new javax.swing.JTextField();
        txtRePword = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        lblPword = new javax.swing.JLabel();
        lblRePword = new javax.swing.JLabel();
        radioCustomer = new javax.swing.JRadioButton();
        radioSupplier = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblUser.setText("username:");

        lblPword.setText("password:");

        lblRePword.setText("re-enter password :");

        radioCustomer.setText("Customer");
        radioCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCustomerActionPerformed(evt);
            }
        });

        radioSupplier.setText("Supplier");
        radioSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSupplierActionPerformed(evt);
            }
        });

        btnBack.setText("< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRePword)
                            .addComponent(lblPword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUser, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPword, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRePword, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioSupplier)
                            .addComponent(radioCustomer)))
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPword))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRePword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRePword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreate)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if (!usernamePatternCorrect()){
            txtUser.setBorder(borderWarn);
            lblUser.setForeground(Color.red);
            txtPword.setBorder(borderDefault);
            txtRePword.setBorder(borderDefault);
            lblPword.setForeground(Color.black);
            lblRePword.setForeground(Color.black);
            JOptionPane.showMessageDialog(null, "Username is not valid!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if (!passwordPatternCorrect()){
            txtPword.setBorder(borderWarn);
            lblPword.setForeground(Color.red);
            txtUser.setBorder(borderDefault);
            lblUser.setForeground(Color.black);
            txtRePword.setBorder(borderDefault);
            lblRePword.setForeground(Color.black);
            JOptionPane.showMessageDialog(null, "Password is not valid!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        else if (!txtPword.getText().equals(txtRePword.getText())){
            txtRePword.setBorder(borderWarn);
            lblRePword.setForeground(Color.red);
            txtUser.setBorder(borderDefault);
            lblUser.setForeground(Color.black);
            txtPword.setBorder(borderDefault);
            lblPword.setForeground(Color.black);
            JOptionPane.showMessageDialog(null, "Password is not consistent!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if (radioCustomer.isSelected()){
            admin.getCustDir().addCustomer(txtPword.getText(),txtUser.getText());
            this.prev_screen.populate();
            txtRePword.setBorder(borderDefault);
            lblRePword.setForeground(Color.black);
            txtUser.setBorder(borderDefault);
            lblUser.setForeground(Color.black);
            txtPword.setBorder(borderDefault);
            lblPword.setForeground(Color.black);
            JOptionPane.showMessageDialog(null, "Customer successfully created!");
        }
        else{
            admin.getSuppDir().addSupplier(txtPword.getText(),txtUser.getText());
            this.prev_screen.populate();
            txtRePword.setBorder(borderDefault);
            lblRePword.setForeground(Color.black);
            txtUser.setBorder(borderDefault);
            lblUser.setForeground(Color.black);
            txtPword.setBorder(borderDefault);
            lblPword.setForeground(Color.black);
            JOptionPane.showMessageDialog(null, "Supplier successfully created!");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void radioCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCustomerActionPerformed
        // TODO add your handling code here:
        radioSupplier.setSelected(false);
    }//GEN-LAST:event_radioCustomerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.remove(this);
        layout.previous(panelRight);
    }//GEN-LAST:event_btnBackActionPerformed

    private void radioSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSupplierActionPerformed
        // TODO add your handling code here:
        radioCustomer.setSelected(false);
    }//GEN-LAST:event_radioSupplierActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblPword;
    private javax.swing.JLabel lblRePword;
    private javax.swing.JLabel lblUser;
    private javax.swing.JRadioButton radioCustomer;
    private javax.swing.JRadioButton radioSupplier;
    private javax.swing.JTextField txtPword;
    private javax.swing.JTextField txtRePword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
