/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.*;
import java.time.LocalDate;
import java.util.ArrayList;

/**
 *
 * @author cosette
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private CarCatalog carCatalog;
    private static ArrayList<Car> carList;
    
    public MainJFrame() {
        initComponents();
        carCatalog = new CarCatalog();
        carList = carCatalog.getCarList();
        carList.add(new Car("12345","Toyota","RAV4","Boston",true,"2019",5,LocalDate.parse("2020-10-07")));
        carList.add(new Car("12346","BMW","Z4","Boston",true,"2018",2,LocalDate.parse("2023-10-09")));
        carList.add(new Car("12347","Bentley","Bentayga","Boston",true,"2018",4,LocalDate.parse("2023-08-01")));
        carList.add(new Car("12348","Audi","A3","Boston",true,"2017",4,LocalDate.parse("2022-03-01")));
        carList.add(new Car("12349","GMC","Acadia","Boston",false,"2015",6,LocalDate.parse("2020-07-01")));
        carList.add(new Car("12350","Toyota","RAV4","Cambridge",true,"2020",5,LocalDate.parse("2025-11-11")));
        carList.add(new Car("12351","Toyota","RAV4","Boston",true,"2019",5,LocalDate.parse("2023-12-01")));
        carList.add(new Car("12352","GMC","Acadia","Cambridge",false,"2016",6,LocalDate.parse("2021-08-02")));
        carList.add(new Car("12353","Toyota","RAV4","Boston",true,"2018",5,LocalDate.parse("2023-10-01")));
        carList.add(new Car("12354","Audi","A3","Boston",true,"2018",4,LocalDate.parse("2023-01-10")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnFindFirstAvail = new javax.swing.JButton();
        btnAvailUnavail = new javax.swing.JButton();
        btnManuYear = new javax.swing.JButton();
        btnSeats = new javax.swing.JButton();
        btnSerialNum = new javax.swing.JButton();
        btnModelNum = new javax.swing.JButton();
        btnManuDirectory = new javax.swing.JButton();
        btnLastUpdatedTime = new javax.swing.JButton();
        btnAvailByCity = new javax.swing.JButton();
        btnExpiredCert = new javax.swing.JButton();
        btnByBrand = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFindFirstAvail.setText("Find the First Available Car");
        btnFindFirstAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindFirstAvailActionPerformed(evt);
            }
        });

        btnAvailUnavail.setText("Cars Availability");
        btnAvailUnavail.setMaximumSize(new java.awt.Dimension(213, 29));
        btnAvailUnavail.setMinimumSize(new java.awt.Dimension(213, 29));
        btnAvailUnavail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailUnavailActionPerformed(evt);
            }
        });

        btnManuYear.setText("Cars by YOM ");
        btnManuYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManuYearActionPerformed(evt);
            }
        });

        btnSeats.setText("Seats Preference");
        btnSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeatsActionPerformed(evt);
            }
        });

        btnSerialNum.setText("Serial Number");
        btnSerialNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerialNumActionPerformed(evt);
            }
        });

        btnModelNum.setText("Model Number");
        btnModelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelNumActionPerformed(evt);
            }
        });

        btnManuDirectory.setText("Manufacturer Directory");
        btnManuDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManuDirectoryActionPerformed(evt);
            }
        });

        btnLastUpdatedTime.setText("Last Updated Time");
        btnLastUpdatedTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastUpdatedTimeActionPerformed(evt);
            }
        });

        btnAvailByCity.setText("Available Cars by City ");
        btnAvailByCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailByCityActionPerformed(evt);
            }
        });

        btnExpiredCert.setText("Expired Maintenance Cert.");
        btnExpiredCert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpiredCertActionPerformed(evt);
            }
        });

        btnByBrand.setText("Cars by Brand");
        btnByBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnByBrandActionPerformed(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Create");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAvailUnavail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManuYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSerialNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModelNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManuDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLastUpdatedTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAvailByCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExpiredCert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnByBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFindFirstAvail, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFindFirstAvail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAvailUnavail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnByBrand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManuYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSerialNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModelNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManuDirectory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLastUpdatedTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAvailByCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExpiredCert)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindFirstAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindFirstAvailActionPerformed
        // TODO add your handling code here:
        FindFirstAvailJPanel findFirstAvailJPanel = new FindFirstAvailJPanel(carCatalog);
        jSplitPane.setRightComponent(findFirstAvailJPanel);
    }//GEN-LAST:event_btnFindFirstAvailActionPerformed

    private void btnAvailUnavailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailUnavailActionPerformed
        // TODO add your handling code here:
        AvailabilityJPanel availabilityJPanel = new AvailabilityJPanel(carCatalog);
        jSplitPane.setRightComponent(availabilityJPanel);
    }//GEN-LAST:event_btnAvailUnavailActionPerformed

    private void btnManuYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManuYearActionPerformed
        // TODO add your handling code here:
        YOMJPanel yomJPanel = new YOMJPanel(carCatalog);
        jSplitPane.setRightComponent(yomJPanel);
    }//GEN-LAST:event_btnManuYearActionPerformed

    private void btnByBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnByBrandActionPerformed
        // TODO add your handling code here:
        ByBrandJPanel byBrandJPanel = new ByBrandJPanel(carCatalog);
        jSplitPane.setRightComponent(byBrandJPanel);
    }//GEN-LAST:event_btnByBrandActionPerformed

    private void btnSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeatsActionPerformed
        // TODO add your handling code here:
        SeatsJPanel seatsJPanel = new SeatsJPanel(carCatalog);
        jSplitPane.setRightComponent(seatsJPanel);
    }//GEN-LAST:event_btnSeatsActionPerformed

    private void btnSerialNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerialNumActionPerformed
        // TODO add your handling code here:
        SerialNumJPanel serialNumJPanel = new SerialNumJPanel(carCatalog);
        jSplitPane.setRightComponent(serialNumJPanel);
    }//GEN-LAST:event_btnSerialNumActionPerformed

    private void btnModelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelNumActionPerformed
        // TODO add your handling code here:
        ModelNumJPanel modelNumJPanel = new ModelNumJPanel(carCatalog);
        jSplitPane.setRightComponent(modelNumJPanel);
    }//GEN-LAST:event_btnModelNumActionPerformed

    private void btnManuDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManuDirectoryActionPerformed
        // TODO add your handling code here:
        ManuDirectoryJPanel manuDirectoryJPanel = new ManuDirectoryJPanel(carCatalog);
        jSplitPane.setRightComponent(manuDirectoryJPanel);
    }//GEN-LAST:event_btnManuDirectoryActionPerformed

    private void btnLastUpdatedTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastUpdatedTimeActionPerformed
        // TODO add your handling code here:
        LastTimeJPanel lastTimeJPanel = new LastTimeJPanel(carCatalog);
        jSplitPane.setRightComponent(lastTimeJPanel);
    }//GEN-LAST:event_btnLastUpdatedTimeActionPerformed

    private void btnAvailByCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailByCityActionPerformed
        // TODO add your handling code here:
        CityJPanel cityJPanel = new CityJPanel(carCatalog);
        jSplitPane.setRightComponent(cityJPanel);
    }//GEN-LAST:event_btnAvailByCityActionPerformed

    private void btnExpiredCertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiredCertActionPerformed
        // TODO add your handling code here:
        CertJPanel certJPanel = new CertJPanel(carCatalog);
        jSplitPane.setRightComponent(certJPanel);
    }//GEN-LAST:event_btnExpiredCertActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CreateJPanel createJPanel = new CreateJPanel(carCatalog);
        jSplitPane.setRightComponent(createJPanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UpdateJPanel updateJPanel = new UpdateJPanel(carCatalog);
        jSplitPane.setRightComponent(updateJPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**jSplitPaneram args the command line arguments
     */
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailByCity;
    private javax.swing.JButton btnAvailUnavail;
    private javax.swing.JButton btnByBrand;
    private javax.swing.JButton btnExpiredCert;
    private javax.swing.JButton btnFindFirstAvail;
    private javax.swing.JButton btnLastUpdatedTime;
    private javax.swing.JButton btnManuDirectory;
    private javax.swing.JButton btnManuYear;
    private javax.swing.JButton btnModelNum;
    private javax.swing.JButton btnSeats;
    private javax.swing.JButton btnSerialNum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
