/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Role.DeliveryManRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PeiLingChiang
 */
public class ManageDMJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem system;
    private DeliveryMan updateDM;
    private UserAccount updateUA;
    
    /**
     * Creates new form ManageDMJPanel
     */
    public ManageDMJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
        populateTable();
        btnSubmit.setEnabled(false);
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblDM.getModel();
        model.setRowCount(0);
        for (DeliveryMan d : system.getDeliveryManDirectory().getDeliveryManList()) {
            Object[] row = new Object[3];
            row[0] = d;
            row[1] = d.getId();
            row[2] = d.getUsername();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassword = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDM = new javax.swing.JTable();
        txtUsername = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 357, 141, -1));

        tblDM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Username"
            }
        ));
        jScrollPane1.setViewportView(tblDM);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 98, 331, 121));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 319, 141, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 281, 141, -1));

        jLabel4.setText("Username");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 324, -1, -1));

        jLabel3.setText("Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 286, -1, -1));

        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 362, -1, -1));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 394, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 225, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 225, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText(" Manage DeliveryMan");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 50, -1, -1));

        btnSubmit.setText("Submit Update");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 394, 116, -1));

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 394, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().length()==0 ||
            txtUsername.getText().length()==0 ||
            txtPassword.getText().length()==0){

            JOptionPane.showMessageDialog(null, "Please enter all fields!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        if (!system.getUserAccountDirectory().checkIfUsernameIsUnique(txtUsername.getText())){
            JOptionPane.showMessageDialog(null, "Please enter a unique username!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        system.getDeliveryManDirectory().createDeliveryMan(txtName.getText(), txtUsername.getText());
        system.getUserAccountDirectory().createUserAccount(txtUsername.getText(), txtPassword.getText(), userAccount.getEmployee(), new DeliveryManRole());
        JOptionPane.showMessageDialog(null, "Successfully created!");
        populateTable();
        
        txtName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int row = tblDM.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        btnSubmit.setEnabled(true);
        btnCreate.setEnabled(false);
        txtUsername.setEnabled(false);

        updateDM = (DeliveryMan) tblDM.getValueAt(row, 0);
        updateUA = system.getUserAccountDirectory().findUser(updateDM.getUsername());
        txtName.setText(updateDM.getName());
        txtUsername.setText(updateDM.getUsername());
        txtPassword.setText(updateUA.getPassword());
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblDM.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DeliveryMan d = (DeliveryMan) tblDM.getValueAt(row, 0);
        system.getDeliveryManDirectory().getDeliveryManList().remove(d);
        system.getUserAccountDirectory().getUserAccountList().remove(system.getUserAccountDirectory().findUser(d.getUsername()));
        JOptionPane.showMessageDialog(null, "Successfully deleted!");
        populateTable();
        
        txtName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        updateDM.setName(txtName.getText());
        updateUA.setPassword(txtPassword.getText());
        JOptionPane.showMessageDialog(null, "Successfully updated!");
        populateTable();

       
        btnSubmit.setEnabled(false);
        btnCreate.setEnabled(true);
        txtUsername.setEnabled(true);
        
        txtName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDM;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
