/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantManager;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PeiingChiang
 */
public class ManageRMJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem system;
    private RestaurantManager updateRM;
    private UserAccount updateUA;
    
    /**
     * Creates new form ManageRMJPanel
     */
    public ManageRMJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
        populateTable();
        btnSubmit.setEnabled(false);
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblRM.getModel();
        model.setRowCount(0);
        for (RestaurantManager r : system.getRestaurantManagerDirectory().getRestaurantManagerList()) {
            Object[] row = new Object[4];
            row[0] = r;
            row[1] = r.getRestaurant();
            row[2] = r.getId();
            row[3] = r.getUsername();
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRM = new javax.swing.JTable();
        txtPassword = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRestaurant = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 355, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 254, 141, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 318, 141, -1));

        tblRM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Restaurant", "ID", "Username"
            }
        ));
        jScrollPane1.setViewportView(tblRM);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 71, 331, 121));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 350, 141, -1));

        btnSubmit.setText("Submit Update");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 394, 116, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText(" Manage Restaurant Managers");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 23, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 198, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 198, -1, -1));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 394, -1, -1));

        jLabel3.setText("Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 259, -1, -1));

        jLabel4.setText("Username");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 323, -1, -1));

        jLabel2.setText("Restaurant");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 291, -1, -1));
        add(txtRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 286, 141, -1));

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 394, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        updateRM.setName(txtName.getText());
        updateUA.setPassword(txtPassword.getText());
        
        JOptionPane.showMessageDialog(null, "Successfully updated!");
        populateTable();

        btnSubmit.setEnabled(false);
        btnCreate.setEnabled(true);
        txtRestaurant.setEnabled(true);
        txtUsername.setEnabled(true);
        
        txtName.setText("");
        txtRestaurant.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblRM.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        RestaurantManager r = (RestaurantManager) tblRM.getValueAt(row, 0);
        system.getRestaurantDirectory().getRestaurantList().remove(r.getRestaurant());
        system.getRestaurantManagerDirectory().getRestaurantManagerList().remove(r);
        system.getUserAccountDirectory().getUserAccountList().remove(system.getUserAccountDirectory().findUser(r.getUsername()));
        JOptionPane.showMessageDialog(null, "Successfully deleted!");
        populateTable();
        
        txtName.setText("");
        txtRestaurant.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int row = tblRM.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        btnSubmit.setEnabled(true);
        btnCreate.setEnabled(false);
        txtRestaurant.setEnabled(false);
        txtUsername.setEnabled(false);

        updateRM = (RestaurantManager) tblRM.getValueAt(row, 0);
        updateUA = system.getUserAccountDirectory().findUser(updateRM.getUsername());
        txtName.setText(updateRM.getName());
        txtRestaurant.setText(updateRM.getRestaurant().toString());
        txtUsername.setText(updateRM.getUsername());
        txtPassword.setText(updateUA.getPassword());
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().length()==0 || 
            txtRestaurant.getText().length()==0 || 
            txtUsername.getText().length()==0 ||
            txtPassword.getText().length()==0){
            
            JOptionPane.showMessageDialog(null, "Please enter all fields!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        if (!system.getUserAccountDirectory().checkIfUsernameIsUnique(txtUsername.getText())){
            JOptionPane.showMessageDialog(null, "Please enter a unique username!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        // check restaurant exist or not
        if (system.getRestaurantDirectory().getRestaurantList()!= null){
            for (Restaurant r:system.getRestaurantDirectory().getRestaurantList()){
                if (r.getName().equals(txtRestaurant.getText())){
                    JOptionPane.showMessageDialog(null, "Duplicate Restaurant Name!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        
        system.getRestaurantManagerDirectory().createRestaurantManager(txtName.getText(), txtUsername.getText(), txtRestaurant.getText());
        system.getUserAccountDirectory().createUserAccount(txtUsername.getText(), txtPassword.getText(), userAccount.getEmployee(), new AdminRole());
        JOptionPane.showMessageDialog(null, "Successfully created!");
        populateTable();
        
        txtName.setText("");
        txtRestaurant.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRM;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRestaurant;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
