/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem system;
    private Restaurant restaurant;
    
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public CustomerAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.system = system;
        jComboBox.removeAllItems();
        Object[] array = system.getRestaurantDirectory().getRestaurantList().toArray();
        for(int i=0; i<array.length;i++){
            jComboBox.addItem(array[i].toString());
        }
    }
    
    public void populateTblFood(Restaurant r){
        DefaultTableModel dtm = (DefaultTableModel)tblFood.getModel();
        dtm.setRowCount(0);
        for(String s : r.getMenu()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=s;
            dtm.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFood = new javax.swing.JTable();
        btnSelect = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Restaurant:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 127, 30));

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        tblFood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Menu"
            }
        ));
        jScrollPane2.setViewportView(tblFood);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 190, 290));

        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));

        btnView.setText("View Order >");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        String selectedR = jComboBox.getSelectedItem().toString();
        ArrayList<Restaurant> list = system.getRestaurantDirectory().getRestaurantList();
        for (int i=0; i < list.size();i++){
            if (list.get(i).toString().equals(selectedR) ){
                populateTblFood(list.get(i));
                restaurant = list.get(i);
            }
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        
        if(tblFood.getSelectedRowCount()<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            int row = tblFood.getSelectedRow();
            String orderItem = (String) tblFood.getValueAt(row, 0);
           
            OrderRequest orderRequest = new OrderRequest();
            orderRequest.setOrderItem(orderItem);
            orderRequest.setSender(userAccount);
            orderRequest.setStatus("Unapproved");
            
            for(UserAccount ua : system.getUserAccountDirectory().getUserAccountList()){
                if (ua.getUsername().equals(restaurant.getRm().getUsername())){
                    orderRequest.setReceiver(ua);
                    ua.getWorkQueue().getOrderRequestList().add(orderRequest);
                }
            }
            userAccount.getWorkQueue().getOrderRequestList().add(orderRequest);
            
            JOptionPane.showMessageDialog(null, "Successfully ordered!");
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("ReviewOrder",new ReviewOrderJPanel(userProcessContainer, userAccount, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFood;
    // End of variables declaration//GEN-END:variables
}
